# Generated by Django 5.2.7 on 2025-10-14 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceProcessingJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("ocr_engine", models.CharField(default="tesseract", max_length=50)),
                ("llm_provider", models.CharField(default="openai", max_length=50)),
                ("llm_model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ocr_text", models.TextField(blank=True, null=True)),
                ("ocr_confidence", models.FloatField(blank=True, null=True)),
                ("ocr_processing_time", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Processing Job",
                "verbose_name_plural": "Invoice Processing Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_file_name", models.CharField(max_length=255)),
                (
                    "unique_invoice_number",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("invoice_date", models.CharField(max_length=50)),
                ("due_date", models.CharField(max_length=50)),
                (
                    "purchase_order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "invoice_currency_code",
                    models.CharField(default="USD", max_length=10),
                ),
                (
                    "total_value_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_tax_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_payable_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_data",
                        to="ocr_app.invoiceprocessingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Data",
                "verbose_name_plural": "Invoice Data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_description", models.CharField(max_length=500)),
                (
                    "product_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity_shipped", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "extended_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tax_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_value_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "invoice_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="ocr_app.invoicedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Item",
                "verbose_name_plural": "Line Items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("module", models.CharField(blank=True, max_length=100, null=True)),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ocr_app.invoiceprocessingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Log",
                "verbose_name_plural": "Processing Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PartyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("buyer", "Buyer"),
                            ("ship_to", "Ship To"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("tax_id_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "registration_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "invoice_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="ocr_app.invoicedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Information",
                "verbose_name_plural": "Party Information",
                "unique_together": {("invoice_data", "party_type")},
            },
        ),
    ]
